### ISSUE TITLE
Prepare gem for open source

### ISSUE THREAD

**Issue by vinistock** [Shopify/ruby-lsp-rails#10]
Go through the [steps of preparing the gem for being open sourced](https://vault.shopify.io/page/Open-source~dhb2b7f.md#user-content-20-starting-a-new-open-source-project-with-shopify-code).

- https://github.com/Shopify/rails_ruby_lsp/pull/28
- https://github.com/Shopify/rails_ruby_lsp/pull/27

Todo:
- [x] Add a license
- [x] Add a code of conduct
- [x] Review content of README for accuracy and clarity
- [x] Enable branch protection for `main`
- [x] Create shipit stack https://shipit.shopify.io/stacks/new - [link](https://shipit.shopify.io/shopify/rails_ruby_lsp/production)
- [x] Create Helpdesk ticket to make repo public.
- [ ] ~Plan any external announcement/communication.~ This will come later.
- [x] Ensure all GitHub Actions runners are using `ubuntu-latest` rather than `shopify-ubuntu-latest`.

**Comment by andyw8** [comment]
Repo is now public.
