### ISSUE TITLE
puma-dev

### ISSUE THREAD

**Issue by joelmoss** [Shopify/ruby-lsp-rails#184]
I use [puma-dev](https://github.com/puma/puma-dev) to run my rails apps, but ruby-lsp-rails doesn't know that...

> Rails server is not running. To get Rails features in the editor, boot the Rails server

Any way to get it working with puma-dev? thx

**Comment by joelmoss** [comment]
I couldn't tell you exactly how it works, but I think the idea is that there is a global service that runs and manages the registered puma apps. The idea is that there is no explicit start/stop with `rails server` of the server needed.

There is no `tmp/app_uri.txt`, but there is `tmp/puma-dev-*.sock`.

**Comment by andyw8** [comment]
We're changing how the LSP communicates with Rails, so this will no longer be a problem:

https://github.com/Shopify/ruby-lsp-rails/pull/256

(not yet released but should be soon).
