### ISSUE TITLE
Sublime Text CodeLens for running tests is not showing up

### ISSUE THREAD

**Issue by maxim** [Shopify/ruby-lsp-rails#195]
Here's my lsp config:

```json
{
  "show_inlay_hints": true,
  "semantic_highlighting": true,
  "show_code_lens": "phantom", // tried both phantom and annotation
  "clients":
  {
    "ruby-lsp": {
      "enabled": true,
      "command": ["ruby-lsp"],
      "selector": "source.ruby",
      "initializationOptions": {
        "experimentalFeaturesEnabled": true
      }
    }
  }
}
```

Almost everything works:

- ✅ Showing model schema on hover
- ✅ All ruby-lsp features (e.g. rubocop issues)
- ❌ CodeLens to run tests

The gem `ruby-lsp` is outside of Gemfile.
The gem `ruby-lsp-rails` is in development group of Gemfile.

Both current versions: 

```
ruby-lsp (0.12.3)
ruby-lsp-rails (0.2.7)
```

Nothing new shows up when I open test files, even though they're vanilla rails model/controller tests inheriting from `ActiveSupport::TestCase` and `ActionDispatch::IntegrationTest`.

I'm not seeing any codelens-related interaction in the LSP logs. Sublime Text supposedly [supports](https://lsp.sublimetext.io/features/#code-lenses) CodeLenses. Any idea why it may not be working?

**Update:** It's hard to tell what's at fault, the server, the editor, or me. But I just checked, and seems ruby-lsp's own Minitest CodeLens is not showing up either. Maybe this is the wrong place to open the issue.

**Comment by rwols** [comment]
To get code lenses to work, you need to write python glue code to handle the code lens’ command. A JSON configuration like the above is not sufficient. There are some existing python helper packages that handle code lenses.
