### ISSUE TITLE
Schema info not showed on hover

### ISSUE THREAD

**Issue by francescob** [Shopify/ruby-lsp-rails#240]
As title says, when hovering on an active record class schema information is not shows, however browsing to http://localhost:3000/ruby_lsp_rails/models/User
show all the correct info:

`{
"columns": [
[
"id",
"integer"
],
[
"email",
"string"
],
[
"encrypted_password",
"string"
],
[
"reset_password_token",
"string"
],

...
}`

app is a fairly new and small rails 7.1 app, with ruby 3.2.2
Visual Studio Code 1.86.9 running on OpenSuse Tumbleweed, ruby lsp extension version 0.5.9

**Comment by PratikVishwakarma22** [comment]
How did you resolve the issue, it doesn't work for me.
