### ISSUE TITLE
Add support for shoulda-context rails gem

### ISSUE THREAD

**Issue by domingo2000** [Shopify/ruby-lsp-rails#244]
Currently the test run functionallity does not support shoulda-context should statements. It would be nice to integrate this extension to be able to recognize tests from other statements like `should` and not only `test`.

Shouda-Context Repository: https://github.com/thoughtbot/shoulda-context

# Current Behaviour:
When using shoulda-context the tests are not parsed correctly and `run` option in file detect no tests

# Expected Behaviour:
Be able to parse tests present in shoulda-context syntax and run from the file with  `run` option

# How to reproduce
1. Create a rails project
2. Install shoulda-context gem
3. Create a test with the following code

```
require "test_helper"

class CalculatorTest < Minitest::Test
  should "true" do
    assert true
  end
end

```

The tests pannel in vscode will show 

![image](https://github.com/Shopify/ruby-lsp-rails/assets/40220174/7e06b9a1-8b02-44b2-95ce-0bd245fb52e5)

**Comment by vinistock** [comment]
Thank you for the feature suggestion!

Shoulda can be used outside of a Rails context in other types of Ruby projects. This functionality would be better fitted for a separate [Ruby LSP addon](https://github.com/Shopify/ruby-lsp/blob/main/ADDONS.md) (e.g.: `ruby-lsp-shoulda`).

It's a similar scenario as RSpec, which can be used on any project. The [ruby-lsp-rspec addon](https://github.com/st0012/ruby-lsp-rspec) handles the RSpec syntax.
