### ISSUE TITLE
Puma custom configuration is not supported

### ISSUE THREAD

**Issue by beauraF** [Shopify/ruby-lsp-rails#247]
Hello 👋

First, thanks a lot for all this great work!

We would love to use `ruby-lsp-rails` on our codebase, but the way the [host discoverability is currently made](https://github.com/Shopify/ruby-lsp-rails/blob/b03cce00a272d1107f727b893a6118bbe375f8a4/lib/ruby_lsp_rails/railtie.rb#L22) does not work with a custom puma configuration (e.g. to enable SSL).

Taking this configuration as an example:
```ruby
# frozen_string_literal: true

# This configuration file will be evaluated by Puma. The top-level methods that
# are invoked here are part of Puma's configuration DSL. For more information
# about methods provided by the DSL, see https://puma.io/puma/Puma/DSL.html.

threads 1, 1

ssl_bind 'localhost', ENV.fetch('PORT', 3000), { cert: ENV.fetch('HTTPS_CERT'), key: ENV.fetch('HTTPS_PRIVATE_KEY') }

# Specifies the `environment` that Puma will run in.
environment ENV.fetch('RAILS_ENV', 'development')

# Allow puma to be restarted by `bin/rails restart` command.
plugin :tmp_restart

pidfile ENV['PIDFILE'] if ENV['PIDFILE']

# Specifies a very generous `worker_timeout` so that the worker
# isn't killed by Puma when suspended by a debugger.
worker_timeout 3600
```

`ruby-lsp-rails` will not take into account that my app is running on HTTPS.

As a workaround we can:
```ruby
# frozen_string_literal: true

# This configuration file will be evaluated by Puma. The top-level methods that
# are invoked here are part of Puma's configuration DSL. For more information
# about methods provided by the DSL, see https://puma.io/puma/Puma/DSL.html.

threads 1, 1

bind 'tcp://localhost:3000'
ssl_bind 'localhost', 3001, { cert: ENV.fetch('HTTPS_CERT'), key: ENV.fetch('HTTPS_PRIVATE_KEY') }

# Specifies the `environment` that Puma will run in.
environment ENV.fetch('RAILS_ENV', 'development')

# Allow puma to be restarted by `bin/rails restart` command.
plugin :tmp_restart

pidfile ENV['PIDFILE'] if ENV['PIDFILE']

# Specifies a very generous `worker_timeout` so that the worker
# isn't killed by Puma when suspended by a debugger.
worker_timeout 3600
```

But it will introduce a lot of change internally as we will have to stop using port 3000 (reserved for `ruby-lsp-rails`) and use 3001 instead.

I haven't come up with a good idea yet, but I'll keep thinking about it. But if you have any insights, I'd be more than happy to implement the needed changes :)

**Comment by vinistock** [comment]
Thanks for the detailed bug report!

We're in the process of [changing how our communication with the Rails application works](https://github.com/Shopify/ruby-lsp-rails/pull/230), which will fix this issue.

Basically, we're moving away from depending on the Rails server and instead spawning a custom lightweight server through Rails runner that will serve the LSP exclusively. That should eliminate the coupling with web servers and their configurations.

**Comment by beauraF** [comment]
Thanks @vinistock. That's great news!

**Comment by beauraF** [comment]
Fixed by https://github.com/Shopify/ruby-lsp-rails/pull/256. Thanks a lot @andyw8 ! Just deployed on our codebase, seems to work like a charm. 🙏
