### ISSUE TITLE
Hover fetching incorrect definitions for homonymous methods and `&:` block

### ISSUE THREAD

**Issue by wimdavies** [Shopify/ruby-lsp-rails#267]
hi there,

In my Rails app, I was prototyping a class that uses `HTTParty` to wrap an external API and return the resource in a useable form for the rest of my app. In doing so, I noticed a few issues with the definitions available to me on hover. Here's the API client (located in `/lib/clients`):
```ruby
require "httparty"
require "active_support"
require "active_support/core_ext/hash/keys"
require "active_support/core_ext/string/inflections"

class VandaClient
  include HTTParty
  base_uri "https://api.vam.ac.uk/v2"
  default_timeout 10

  def self.retrieve_single_object_record(system_number)
    response = self.get("/museumobject/#{system_number}")
    JSON.parse(response.parsed_response.deep_transform_keys(&:underscore).to_json, object_class: OpenStruct)
  end
end
```
(I know OpenStruct is advised against; this is just for prototyping purposes...)

Issues:
1. On hover over `.deep_transform_keys`, I am offered `Rails Document: ActionController::Parameters#deep_transform_keys`. However, as you can see from the require call, this method is actually being derived from `ActiveSupport::CoreExt`.

2. On hover over the `underscore` method called in the `Symbol#to_proc` block argument to the above, I'm offered the same `Rails Document: ActionController::Parameters#deep_transform_keys` instead of the relevant method from the string module of `core_ext`

3. Hovering over any of the `require`s and their arguments gets me `Rails Document: ActionController::Parameters#require` (rather than the basic ruby `require`, which is what I would expect if I were to get anything). `documentLink`  works as expected for any of the paths there, however.

4. Hovering over the `.get` call gives me: 
'get
Definitions: Rails Document: 
ActionController::TestCase::Behavior#get
Rails Document: ActionDispatch::Integration::RequestHelpers#get
Rails Document: ActionDispatch::Routing::Mapper::HttpHelpers#get'
However, this method is derived from none of these Rails modules, but from `HTTParty`.

Additionally:

- The definitions for the other `HTTParty` methods are empty (`base_uri`, `default_timeout`) or not offered at all (`parsed_response`). I suspect this could partly be a consequence of how HTTParty structures its modules. The same might go for why 'Definitions' is present  but empty in the `get` hover.
- `JSON`'s definition is available on hover, but nothing is offered for the `.parse` or `.to_json` calls. Again, this could be to do with how HTTParty requires JSON in.

I appreciate HTTParty's business is way out of your hands; I mention that behaviour just for background. However, the 'Rails Document' behaviour is surprising as a user, and I thought it might be worth raising an issue for it. A few questions this prompts for me:

- Are you able to say why `ruby-lsp-rails` returns one Rails definition of a method, but not its identically-named sibling? This is even more unexpected when the correct one is explicitly required in the file.
- Is it expected behaviour for the current state of the gem (or of `ruby-lsp`) to incorrectly define methods when called via `&:`? 
- Why does the gem give a Rails definition for standard Ruby's `require`?

Versioning info: 
this project was recently bumped to use the install of ruby-lsp-rails v0.3.0 that is custom bundled in by the latest version of the VS Code extension. The project also has `ruby-lsp-rspec` installed, so Gemfile.lock contains the following:
```
ruby-lsp (0.14.1)
      language_server-protocol (~> 3.17.0)
      prism (>= 0.22.0, < 0.25)
      sorbet-runtime (>= 0.5.10782)
    ruby-lsp-rspec (0.1.10)
      ruby-lsp (~> 0.14.0)
```

Thanks!

**Comment by vinistock** [comment]
This is no longer going to show up since #472. We removed the DSL document links on hover and will now rely on the base Ruby LSP to show documentation based on indexed entries.
