### ISSUE TITLE
server.rb spinning on 100% CPU trying to create tempfiles

### ISSUE THREAD

**Issue by mttkay** [Shopify/ruby-lsp-rails#278]
I am running into a bug that I can consistently reproduce, where the ruby-lsp-server component will start up and not terminate, consuming an entire CPU:

![Screenshot from 2024-02-29 09-53-42](https://github.com/Shopify/ruby-lsp-rails/assets/102802/46a4c4b3-6509-4139-8cdc-3442f53ce44f)

I took a CPU profile and found that it seems to spend most of that time trying to create a temp dir in an `asdf` managed directory:

```
Time since start: 29s. Press Ctrl+C to stop.
Summary of profiling data so far:
% self  % total  name
 54.12    59.97  rescue in block in mkdir_p - /home/mk/.asdf/installs/ruby/3.2.3/lib/ruby/gems/3.2.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/store.rb:0
 23.32    23.32  directory? [c function] - (unknown)
  9.22    13.54  mkdir [c function] - (unknown)
  4.32     4.32  initialize [c function] - (unknown)
  4.18     4.18  dirname [c function] - (unknown)
  2.19     2.19  pid [c function] - (unknown)
  1.18   100.00  dump_data - /home/mk/.asdf/installs/ruby/3.2.3/lib/ruby/gems/3.2.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/store.rb:110
  0.63     0.84  rescue in dump_data - /home/mk/.asdf/installs/ruby/3.2.3/lib/ruby/gems/3.2.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/store.rb:0
  0.31    73.83  block in mkdir_p - /home/mk/.asdf/installs/ruby/3.2.3/lib/ruby/gems/3.2.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/store.rb:126
  0.24     0.24  === [c function] - (unknown)
  0.17    93.42  mkdir_p - /home/mk/.asdf/installs/ruby/3.2.3/lib/ruby/gems/3.2.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/store.rb:127
  0.07     0.07  raise [c function] - (unknown)
  0.03     0.03  rand [c function] - (unknown)
  0.00   100.00  transaction - /home/mk/.asdf/installs/ruby/3.2.3/lib/ruby/gems/3.2.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/store.rb:57
  0.00   100.00  synchronize [c function] - (unknown)
  0.00   100.00  setup - /home/mk/.asdf/installs/ruby/3.2.3/lib/ruby/gems/3.2.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache.rb:46
  0.00   100.00  setup - /home/mk/.asdf/installs/ruby/3.2.3/lib/ruby/gems/3.2.0/gems/bootsnap-1.18.3/lib/bootsnap.rb:76
  0.00   100.00  require_relative [c function] - (unknown)
  0.00   100.00  require [c function] - (unknown)
  0.00   100.00  require - <internal:/home/mk/.asdf/installs/ruby/3.2.3/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:165
Wrote raw data to /home/mk/.cache/rbspy/2024-02-29-TTLMXZcaex.raw.gz
Wrote formatted output to _gi/ruby-lsp.3.json
```

I have to TERM the process every single time it starts up.

Gemfile:

```ruby
  gem 'ruby-lsp', "~> 0.14.2", require: false, feature_category: :tooling

  gem 'ruby-lsp-rails', "~> 0.3.0", feature_category: :tooling

  gem 'ruby-lsp-rspec', "~> 0.1.10", require: false, feature_category: :tooling
```

I use VSCode with the `ruby-lsp` v0.5.11 extension.

**Comment by Earlopain** [comment]
Hi there, I have a hunch on what this might be. Do you have a large folder inside the workspace directory (like from activestorage)? I ran into something similar at https://github.com/Shopify/vscode-ruby-lsp/issues/1035.

I would try to disable [bootsnap](https://github.com/Shopify/bootsnap) or add that folder to `BOOTSNAP_IGNORE_DIRECTORIES` if you can identify it. You might need to do something similar for ruby-lsp by using the `.index.yml` file ([docs](https://github.com/Shopify/ruby-lsp?tab=readme-ov-file#configuring-code-indexing)). Strange how this only happens when using the server runner.

Hope that helps and gives you some pointers for additional troubleshooting.

**Comment by vinistock** [comment]
This may also be the bug fixed in [v0.3.2](https://github.com/Shopify/ruby-lsp-rails/releases/tag/v0.3.2). Could you please test the new version and let us know if your issue is fixed?

**Comment by mttkay** [comment]
I mean, I think we know what the problem is already, it's that `tmp/cache` is a broken symlink, so it exists, but no file nodes underneath it point anywhere. But indeed, `strace` confirms this, and I also confirmed that this is not a problem specific to `ruby-lsp-rails`. If I run `bin/rails runner` outside of the IDE, it ends up in the same loop:

```shell
write(5, "=== Scanning /home/mk/Projects/w"..., 3391) = 3391
close(5)                                = 0
getpid()                                = 211223
openat(AT_FDCWD, "/tmp/ruby-lsp.log", O_WRONLY|O_CREAT|O_TRUNC|O_CLOEXEC, 0666) = 5
ioctl(5, TCGETS, 0x7ffc745af370)        = -1 ENOTTY (Inappropriate ioctl for device)
newfstatat(AT_FDCWD, "/home/mk/Projects/work/gl-gck/gitlab-rails/tmp/cache/bootsnap", 0x7ffc745af240, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/home/mk/Projects/work/gl-gck/gitlab-rails/tmp/cache", 0x7ffc745af240, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/home/mk/Projects/work/gl-gck/gitlab-rails/tmp", {st_mode=S_IFDIR|0755, st_size=250, ...}, 0) = 0
mkdir("/home/mk/Projects/work/gl-gck/gitlab-rails/tmp/cache", 0777) = -1 EEXIST (File exists)
newfstatat(AT_FDCWD, "/home/mk/Projects/work/gl-gck/gitlab-rails/tmp/cache", 0x7ffc745aeee0, 0) = -1 ENOENT (No such file or directory)
```

The log messages are mine (I patched the gem to write a log file into the system tmp dir). The problem is `ENOENT (No such file or directory)`, which breaks bootsnap.

> Disabling bootsnap conditionally should also be possible by examining $PROGRAM_NAME,

Yeah. We would have to patch the application's bootsnap initializer to do this, right? Seems kinda dirty, but I'll propose this as an option, thanks.

I will close this issue here because I confirmed it is not specific to `ruby-lsp-rails`, but I do wonder if the assumption that `bin/rails runner` executions will work in any dev setup holds up well. What if that process tries to open a database connection? Is the assumption that I always run a database on the host OS? This seems to go against where the world of software development is generally headed, which is to utilize containers and run basically nothing on the host OS directly anymore. But that's a broader topic than this issue here.

Thanks for helping out, appreciate it!

**Comment by Earlopain** [comment]
Since bootsnap happens so early in the boot cycle, a initializer is already too late, especially if your application currently follows recommendations for the bootsnap rails setup. Check out the usage section in the docs, that explains what you need to do https://github.com/Shopify/bootsnap?tab=readme-ov-file#usage

This actually mentions that tmp cache MUST be writable, however I'd wager that CPU spinning is still a bug. I would expect it to just raise/crash somewhere. A bug report over there seems like a good idea.

**Comment by mttkay** [comment]
Ah yes, my bad -- I meant to say `boot.rb` not initializer.

Filing an issue against bootsnap makes sense to me. I agree it should not get itself stuck like that. Will cross link here when done.

**Comment by Earlopain** [comment]
Looking at the bootsnap code again, I find it very likely that the following code is responsible for this: https://github.com/Shopify/bootsnap/blob/8394834cd504548aae3b4651587abd823f0495d1/lib/bootsnap/load_path_cache/store.rb#L107-L108

Your strace output seems to back that up as well.
