### ISSUE TITLE
Rails engine would stop responding when the user debugs with ruby/debug

### ISSUE THREAD

**Issue by st0012** [Shopify/ruby-lsp-rails#29]
Because `ruby/debug` stops all threads when it enters a debugging session (e.g. hit a breakpoint), when users are debugging the code, the `ModelsController` won't be able to return anything to Ruby LSP. 

The implications are:

1. The hover feature would stop working once the user starts debugging, which could be confusing.
2. If the user tries to hover multiple times during a debugging session, the requests may queue up, and create huge delays on server once the debugging session is finished.

**Comment by andyw8** [comment]
I wonder if we could use https://github.com/zombocom/rack-timeout with a short timeout (~1s), but only applied to queries with a path beginning `/ruby-lsp/`.

**Comment by st0012** [comment]
That will only work with our debugger fork though because `ruby/debug` freezes all threads, including Timeout's. So when the debugger is activated there will never be timeout.

**Comment by vinistock** [comment]
What if a user puts a debug statement in a model we haven't autoloaded yet? Or if the runner is reloaded while a debug statement is still present? Wouldn't we be subject to the same issue?
