### ISSUE TITLE
Modifying `structure.sql` doesn't trigger an update event

### ISSUE THREAD

**Issue by Earlopain** [Shopify/ruby-lsp-rails#326]
Reloading for `schema.rb` and `structure.sql` was added in #282. The server however only listens for `*.rb` changes so it will never reload for `strucutre.sql` changes.

Culprit in the server code: https://github.com/Shopify/ruby-lsp/blob/729df3e909368ee09ba1315fa0a208dda52110ea/lib/ruby_lsp/server.rb#L206-L212

Demo video:

[Screencast_20240409_154242.webm](https://github.com/Shopify/ruby-lsp-rails/assets/14981592/dbef5e0f-1c10-44a3-ae9a-4ab8d734f32e)

**Comment by Earlopain** [comment]
Yes, that sounds fine I think. I will start with the change in `ruby-lsp`. I see now how addons would send the request, just throw it in the `message_queue`.

**Comment by Earlopain** [comment]
I think I understand it now, the ID is just what will be set in the response in order to connect request/response pairs (see docs of Reponse just below). In that case, transparently setting the id isn't really helpful if someone wants to react to a certain response. OTOH, I'm not sure if you even have a chance to get at that response if you wanted to in an addon

I think it makes most sense to just accept strings as well. Addons should maintain their own counter and namespace their requests, if they even need a counter. For this particular issue a manual id like in my example is good since only one request will be sent anyways and I don't care about the response.

What do you think?

**Comment by vinistock** [comment]
Indeed, there's no way for an addon to receive a response back for their request yet. Maybe we can use a pattern as part of the ID, so that if one day we look into delegating the responses back to addons, it's easy to figure it out. For example, we could use the addon name.

For the time being, yeah, let's move forward with some generic string ID, like `"request-file-watching"`.
