### ISSUE TITLE
Failure for `sorbet-runtime` on new Rails app

### ISSUE THREAD

**Issue by andyw8** [Shopify/ruby-lsp-rails#336]
I noticed when testing on a new Rails app:

```
2024-04-16 13:17:57.057 [info] (rails7) Ruby LSP Rails failed to initialize server: <internal:/opt/rubies/3.2.1/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require': cannot load such file -- sorbet-runtime (LoadError)
```

I suspect this wasn't noticed previously because `sorbet-runtime` was already being required by something else.

**Comment by vinistock** [comment]
This is strange. First, `sorbet-runtime` is required by `ruby-lsp` way before we even get close to activating any addons.

Second, this is saying that requiring `sorbet-runtime` has failed, which can only happen if the gem is not in the `$LOAD_PATH`, which should be impossible given that we have a dependency on `sorbet-runtime`.

**Comment by andyw8** [comment]
Here's more of the stacktrace:

```
2024-04-16 13:17:57.057 [info] (rails7) Ruby LSP Rails failed to initialize server: <internal:/opt/rubies/3.2.1/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require': cannot load such file -- sorbet-runtime (LoadError)
	from <internal:/opt/rubies/3.2.1/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /Users/andyw8/.gem/ruby/3.2.1/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	from /Users/andyw8/.gem/ruby/3.2.1/gems/zeitwerk-2.6.13/lib/zeitwerk/kernel.rb:34:in `require'
	from /Users/andyw8/.gem/ruby/3.2.1/gems/ruby-lsp-rails-0.3.5/lib/ruby_lsp/ruby_lsp_rails/server.rb:4:in `<main>'
```

So it seems this is because in `server.rb` we're wrongly assuming that `sorbet-runtime` will be available in the main `Gemfile.lock`, when it may only be in `.ruby-lsp/Gemfile.lock`.

So either:
- We need to avoid using Sorbet completely within `server.rb`?
- We need to run `server.rb` but use with `BUNDLE_GEMFILE` set to `.ruby-lsp/Gemfile` ?

**Comment by vinistock** [comment]
Something is still odd about this. If `ruby-lsp-rails` depends on `ruby-lsp`, which then depends on `sorbet-runtime`, it should always be in the `$LOAD_PATH`.

We always boot the language server with `BUNDLE_GEMFILE=.ruby-lsp/Gemfile bundle exec ruby-lsp`, which means all of the dependencies should be available for requiring.

What steps are you taking exactly to reproduce this?

**Comment by andyw8** [comment]
Something like this? https://github.com/Shopify/ruby-lsp-rails/pull/340

**Comment by andyw8** [comment]
FYI @vinistock :



```
puts "1: #{ENV["BUNDLE_GEMFILE"]}"

Bundler.with_unbundled_env do
  puts "2: #{ENV["BUNDLE_GEMFILE"]}"
end

Bundler.with_original_env do
  puts "3: #{ENV["BUNDLE_GEMFILE"]}"
end
```

```
BUNDLE_GEMFILE=.ruby-lsp/Gemfile bundle exec ruby x.rb
1: /Users/andyw8/src/github.com/andyw8/rails7/.ruby-lsp/Gemfile
2: 
3: .ruby-lsp/Gemfile
```
