### ISSUE TITLE
Can't use on windows (due to `setpgrp`)

### ISSUE THREAD

**Issue by krivospitsky** [Shopify/ruby-lsp-rails#348]
I tried to use ruby-lsp in VSCode on windows and got this error:
```
ruby/3.2.0/gems/ruby-lsp-rails-0.3.5/lib/ruby_lsp/ruby_lsp_rails/addon.rb:33 run> terminated with exception (report_on_exception is true):
ruby/3.2.0/gems/ruby-lsp-rails-0.3.5/lib/ruby_lsp/ruby_lsp_rails/runner_client.rb:45:in `setpgrp': setpgrp() function is unimplemented on this machine (NotImplementedError)
```

**Comment by andyw8** [comment]
Thank for the report. This was missed due to https://github.com/Shopify/ruby-lsp-rails/issues/351

**Comment by andyw8** [comment]
@krivospitsky I don't have access to a Windows machine, so could you help me by checking something:

Can you clone this repo, then run `bin/rails c` to start the dummy app, and check if the console successfully starts. In CI it [seems to exit right away](https://github.com/Shopify/ruby-lsp-rails/actions/runs/8822162407/job/24219691837) (look under "Run Tests").

**Comment by andyw8** [comment]
(the above is solved by https://github.com/Shopify/ruby-lsp-rails/pull/353)

**Comment by andyw8** [comment]
@krivospitsky can you give [this branch](https://github.com/Shopify/ruby-lsp-rails/pull/352) a try by adding the following to your Gemfile:

```
gem "ruby-lsp-rails", github: "Shopify/ruby-lsp-rails", branch: "andyw8/fix-ci-setup-for-windows"
```
