### ISSUE TITLE
Autocomplete for Rails routes

### ISSUE THREAD

**Issue by brunnopleffken** [Shopify/ruby-lsp-rails#413]
One thing I really enjoy in RubyMine that is absent [AFAIK] in this extension is the autocompletion of routes.

For example, just after typing `redirect_to` in controllers or `<%= link_to 'My hyperlink',` in templates, RubyMine suggests the routes set in routes.rb, such as `new_user_path`.

I understand it requires some intelligence to determine whether IntelliSense will show classes or methods, or routes. But we all know that when we're working on huge projects, and we have a lot of namespaces and collections, this is great!

**Comment by andyw8** [comment]
Hi @brunnopleffken,

I had started work on this a while ago in https://github.com/Shopify/ruby-lsp-rails/pull/303 and hope to return to it soon.

**Comment by brunnopleffken** [comment]
> I had started work on this a while ago in #303 and hope to return to it soon.

I searched for "routes" in Issues, but not in PRs.
This would be so great! Nice work.
