### ISSUE TITLE
Consider adding a button to launch Rails server in a terminal

### ISSUE THREAD

**Issue by vinistock** [Shopify/ruby-lsp-rails#44]
Currently, we just display a warning mentioning that the Rails server is not running to users. But it would be very nice if we could associate commands in the extension activation event.

For example, if the server is not running, we display a `start server` button. If the `app_uri.txt` file doesn't exist yet, we display a `restart server` button and perform the actions for the user.

This does have downsides though. Letting extensions return commands from activation events means these commands must exist in `vscode-ruby-lsp`, but we certainly don't want to implement commands for every extension that might be created.

Maybe we can treat `ruby-lsp-rails` as a special case and allow only it to register buttons?

**Comment by andyw8** [comment]
Now that we launch Rails automatically via `rails runner`, this is no longer relevant.
