### ISSUE TITLE
Undefined method `source_location` in `resolve_route_info` when using Rails 7

### ISSUE THREAD

**Issue by misham** [Shopify/ruby-lsp-rails#488]
### Description

```
ruby_lsp_rails/server.rb:149:in `resolve_route_info': undefined method `source_location'
```

#### VS Code Version

1.94.2

#### Ruby LSP Extension Version

0.8.6

#### Ruby LSP Server Version

0.20.1

#### Ruby LSP Addons

- Ruby LSP Rails

#### Ruby Version

3.2.2

#### Ruby Version Manager

rvm

#### Installed Extensions

<details>
<summary>Click to expand</summary>

- aws-toolkit-vscode (3.29.0)
- vscode-tailwindcss (0.12.11)
- vscode-modelines (2.0.6)
- circleci (2.8.4)
- vscode-postgres (1.4.3)
- systemd-unit-file (1.0.6)
- posthtml (0.2.1)
- postcss (1.0.9)
- vscode-markdownlint (0.56.0)
- vscode-eslint (3.0.10)
- python-environment-manager (1.2.4)
- gitlens (15.6.2)
- vscode-html-css (2.0.10)
- EditorConfig (0.16.4)
- prettier-vscode (11.0.0)
- auto-rename-tag (0.1.10)
- copilot (1.239.0)
- copilot-chat (0.21.2)
- vscode-pull-request-github (0.98.0)
- gitlab-workflow (5.15.0)
- go (0.42.1)
- gc-excelviewer (4.2.62)
- hcl (0.5.0)
- sentinel (0.3.0)
- terraform (2.33.0)
- prettier-sql-vscode (1.6.0)
- gruvbox (1.19.1)
- vscode-go-template (0.2.1)
- endwise (1.5.1)
- vsc-python-indent (1.18.0)
- linear-connect (1.0.3)
- linear-open-issue (1.0.2)
- rainbow-csv (3.12.0)
- dotenv (1.0.1)
- vscode-azureresourcegroups (0.9.7)
- vscode-docker (1.29.3)
- debugpy (2024.12.0)
- isort (2023.10.1)
- python (2024.16.1)
- vscode-pylance (2024.10.1)
- jupyter (2024.9.1)
- jupyter-keymap (1.1.2)
- jupyter-renderers (1.0.19)
- remote-containers (0.388.0)
- remote-ssh (0.115.0)
- remote-wsl (0.88.4)
- vscode-remote-extensionpack (0.25.0)
- azure-account (0.12.0)
- cpptools (1.22.9)
- cpptools-extension-pack (1.3.0)
- cpptools-themes (2.0.0)
- makefile-tools (0.11.13)
- remote-explorer (0.4.3)
- remote-server (1.5.2)
- test-adapter-converter (0.2.0)
- vscode-typescript-next (5.7.20241017)
- azure-hdinsight (1.1.19)
- gremlins (0.26.0)
- angular-console (18.29.1)
- postman-for-vscode (1.3.0)
- vscode-yaml (1.15.0)
- partial-diff (1.4.3)
- ruby-extensions-pack (0.1.12)
- ruby-lsp (0.8.6)
- code-spell-checker (3.0.1)
- even-better-toml (0.19.2)
- selectline-statusbar (0.0.2)
- json2yaml (0.2.0)
- vim (1.28.1)
- gitblame (11.1.1)
- vscode-postfix-go (0.0.12)
- open-in-external-app (0.10.0)
- markdown-all-in-one (3.6.2)
</details>

#### Ruby LSP Settings

<details>
<summary>Click to expand</summary>

##### Workspace

```json
{}
```

##### User

```json
{
  "enableExperimentalFeatures": false,
  "enabledFeatures": {
    "codeActions": true,
    "diagnostics": true,
    "documentHighlights": true,
    "documentLink": true,
    "documentSymbols": true,
    "foldingRanges": true,
    "formatting": true,
    "hover": true,
    "inlayHint": true,
    "onTypeFormatting": true,
    "selectionRanges": true,
    "semanticHighlighting": true,
    "completion": true,
    "codeLens": true,
    "definition": true,
    "workspaceSymbol": true,
    "signatureHelp": true,
    "typeHierarchy": true,
    "references": true
  },
  "featuresConfiguration": {},
  "addonSettings": {},
  "rubyVersionManager": {
    "identifier": "rvm"
  },
  "customRubyCommand": "",
  "formatter": "rubocop",
  "linters": null,
  "bundleGemfile": "",
  "testTimeout": 30,
  "branch": "",
  "pullDiagnosticsOn": "both",
  "useBundlerCompose": false,
  "bypassTypechecker": false,
  "rubyExecutablePath": "",
  "indexing": {},
  "erbSupport": true
}
```

</details>

### Reproduction steps

Happening with Rails 7.0 app. Started seeing the issue yesterday (Oct 16). Tried to downgrade to several previous versions but now seeing the error consistently.

What would be good ways to reset "things" to previous versions to see which version introduced the issue?

**Code snippet or error message**
```ruby
ruby_lsp_rails/server.rb:149:in `resolve_route_info': undefined method `source_location'
```

**Comment by vinistock** [comment]
@andyw8 it's happening when we invoke `source_location` on a route [here](https://github.com/Shopify/ruby-lsp-rails/blob/0b6dfa615751258aee8a30e3aa5227cc66a60e1b/lib/ruby_lsp/ruby_lsp_rails/server.rb#L150). Do we know when that method was added to Rails? Or do you need to turn on some sort of config to make it available?

**Comment by andyw8** [comment]
It looks like this was added in 7.1:

https://github.com/rails/rails/commit/a00e548da7a1fc6572061a5ac8c3f5679cea0927

@misham We haven't changed any behaviour around this recently, so I'm not sure why you are only seeing it now.

But since Rails 7.0 is EOL, it's not something we would prioritize. However, if you want to investigate, and open a PR, we will gladly review. It may be a very simple fix.

**Comment by vinistock** [comment]
I believe the fix is changing [this line](https://github.com/Shopify/ruby-lsp-rails/blob/0b6dfa615751258aee8a30e3aa5227cc66a60e1b/lib/ruby_lsp/ruby_lsp_rails/server.rb#L149) to

```ruby
if route&.respond_to?(:source_location) && route.source_location
```

If someone is interested in contributing the fix.

**Comment by misham** [comment]
@st0012 I believe my comment was quite civil, even though it ws direct. Happy for feedback on where you thought it was not civil.

My issue with the original comment is that it was dismissive. It was definitely not a suggestion. That's the slap in the face.

WRT investing in this plugin: just because I have not submitted a PR does not mean I have not spent plenty of time debugging issues, troubleshooting setup problems, and helping other people migrate to this plugin and configure their environments to work with it. PRs are not the only measure of helping a project.

I've actually had a very positive previous experience with the maintainers of this project. I believe it was @vinistock who worked through it with grace and kindness. Unfortunately, I can't find the issue in this or the ruby-lsp repo.

Nowhere in my message do I say I expect the maintainers to fix every little bug reported. Nor did I imply that I expect you to fix this issue or deal with every person's weird configuration.

The first line in my response is stating that I'll look at putting a PR together.

Large projects like this one, tend to provide a warning when breaking changes are introduced. Like, say dropping support for a major version of Rails. That way, someone like me can submit a PR ahead of time instead of debugging the tools in the middle of a deadline. I think you'll agree that's not a good place to be.

Just to reiterate the point I was trying to make and I believe you are making as well: it's the respect of other's energy and civil conversation in projects like these that helps them grow. My point is that civil communication goes both ways.

For reference, https://github.com/Shopify/ruby-lsp-rails/issues/488#issuecomment-2422544337 was the civil way to say the team does not have the space to address this issue. The provided code was going above and beyond, but even without the code, that was still a good way to deliver the message.
