### ISSUE TITLE
Add option to move CodeLens to inline instead of above

### ISSUE THREAD

**Issue by donquxiote** [Shopify/ruby-lsp-rails#496]
The code lens to navigate to a view from a controller is really handy! But it's a bit of a nuisance in my project when it looks like an empty line but isn't. 

I'd really appreciate a setting that I could toggle to set the code lens stuff to be next to the controller name instead of just above it.

![Image](https://github.com/user-attachments/assets/306c4675-64e5-4e4f-9171-116530fb39fb)

**Comment by andyw8** [comment]
Hi @donquxiote,

This is a behaviour of VS Code, we don't have control over it. Other people have made this request: https://github.com/microsoft/vscode/issues/90235
