### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by nhorton** [Shopify/ruby-lsp-rails#57]
We run our rails servers inside docker-compose clusters in our dev environments. It looks like this only uses the PIDs to find the server - would be great to have a way to set a port number instead (the server is available via a localhost port).

**Comment by nhorton** [comment]
That would be ideal. Also - thank you all for the work on this. I built my first company on Rails 3 but have been away until late last year, and it is awesome to see folks like Shopify who are really giving back and helping build up the Rails ecosystem.

**Comment by nhorton** [comment]
Wow - that was fast! Thanks!

**Comment by vinistock** [comment]
Sorry, I assumed you were talking about VS Code. Yes, we have a file in the Ruby LSP for community driven instructions for editors other than VS Code. The [NeoVim](https://github.com/Shopify/ruby-lsp/blob/main/EDITORS.md#neovim-lsp) section would be the place to put those.
