### ISSUE TITLE
Explore how to take namespaces into account

### ISSUE THREAD

**Issue by vinistock** [Shopify/ruby-lsp-rails#7]
If we have
```ruby
module Namespace
  def my_method
    User
  end
end
```
and `Namespace::User` is a model, we will not find it because of the nesting. We may need to keep track of the module and class nesting in [locate](https://github.com/Shopify/ruby-lsp/blob/8c000ee1391d26b2a950f19cc3c036a2d283ddc8/lib/ruby_lsp/document.rb#L121) so that we know where the target has been found.

We may also benefit from using Rails' constantize.

**Comment by andyw8** [comment]
This is tricky, but here's an outline of what I'm trying currently.

We need to handle two variants:

Multiple `const_path_ref`s followed by a `const`, e.g.:

```Foo::Bar::User```

Multiple `const_refs` followed by a `const`, e.g.:

```
module Foo
  module Bar
    def something
      User
    end
  end
end
```

We can use `visit_const_ref` and `visit_const_path_ref` add each node into a queue, until we reach a `const` node (`User` in this example). If the node at that point matches the one being hovered over, we map their `value`s, join with `::`, and send that as the query to the engine/middleware.

In the middleware, all that's then needed is to `#constantize` on the string, and rescue if it's fail.

**Comment by vinistock** [comment]
Just one comment: including the nesting should probably be done in the Ruby LSP itself in `Document#locate` because we will need to know the nesting for other things in the future, such as implementation go to definition.

In my head, we'd change `locate` to keep track of the nesting and return it.

**Comment by paracycle** [comment]
Just a quick note that keeping track of nesting is not enough to solve this problem (though it is probably 90% of the solution). To do this right, we would have to resolve constants through the ancestors as well, since you can refer to inherited constants as well.

**Comment by andyw8** [comment]
(putting this on hold for now)
